[package]
name = "starksafe"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">=2.3.0"

[dev-dependencies]
starknet = { version = ">=2.3.0", features = ["testing"] }
cairo_test = "2.11.4"

[[target.starknet-contract]]
starknet = true

[lib]
sierra = true
casm = true

[[test]]
name = "test_account"
starknet = true

[profile.release]
opt-level = 3
codegen-units = 1